services:
  - type: web
    name: rakib-music-api
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y python3 python3-pip ffmpeg
      pip3 install -U yt-dlp
      python3 -m yt_dlp --version
      npm install
    startCommand: node index.js
